version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
- pwsh: dotnet build -c Release

after_test:
- pwsh: dotnet pack $env:APPVEYOR_BUILD_FOLDER\Extended.Dapper -c Release --include-symbols --no-build -o artifacts\nuget

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: NuGet
- path: '**\artifacts\myget\*.nupkg'
  name: MyGet

deploy:

- provider: NuGet
  api_key:
    secure: 
  artifact: NuGet
  on:
    appveyor_repo_tag: true