version: '{build}-{branch}'
image: Visual Studio 2019

branches:
  only:
    - master

skip_branch_with_pr: true

skip_commits:
  files:
    - '**/*.md'

configuration: Release

before_build: dotnet restore

build:
  parallel: true
  project: Extended.Dapper.sln
  publish_nuget: true
  publish_nuget_symbols: true 

after_build: nuget pack

artifacts:
- path: '**\*.nupkg'
  name: NuGet

deploy:
- provider: NuGet
  api_key:
    secure: ZGXyzvCcQNbUmQUxTs5KJ+e6HupDy84yJNO/K64phPf2rg6lgOqx0cLqzgYPFeTG
  artifact: NuGet
  on:
    appveyor_repo_tag: true